import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <header className='flex w-full p-4 justify-between text-sm text-gray-700'>
        {/* Left */}
        <div className='flex space-x-4 items-center ml-3'>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>
        {/* Right */}
        <div className='flex space-x-4 items-center '>
          <p className='link'>Gmail</p>
          <p className='link'>Images</p>

          {/* Icon */}
          <ViewGridIcon className='w-10 h-10 p-2 rounded-full cursor-pointer hover:bg-gray-100' />
          {/* Avatar */}
          <Avatar
            url={
              "https://images.unsplash.com/photo-1623265041640-8973a7afe898?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1051&q=80"
            }
          />
        </div>
      </header>
      {/* Body */}
      <form>
        <Image
          width={100}
          height={100}
          src='https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png'
        />
      </form>
      {/* Footer */}
    </div>
  );
}
